import Link from "next/link";
import { allProducts } from "@/content/collections";
import { confirmedStats, company } from "@/content/company";
import { RfqForm } from "@/components/rfq/RfqForm";
import { Reveal } from "@/components/motion/Reveal";
import { Container } from "@/components/ui/Container";

const catalogueRows = [
  { product: allProducts.find((prod) => prod.slug === "apron-design-01"), title: "Printed aprons", meta: "Apron with Gloves", image: "/images/products/apron-doodle-print.jpg", alt: "Printed cotton apron with an all-over dog print, contrast pocket and tie straps displayed on a mannequin", layout: "photo-first", fit: "cover" },
  { product: allProducts.find((prod) => prod.slug === "kitchen-towel-set-03"), title: "Kitchen towel sets", meta: "Towels", image: "/images/products/kitchen-set-striped.jpg", alt: "Striped cotton apron with matching oven mitts, pot holders, double oven glove and folded kitchen towels", layout: "copy-first", fit: "cover" },
  { product: allProducts.find((prod) => prod.slug === "cushion-design-05"), title: "Printed cushions", meta: "Cushions", image: "/images/products/cushion-palm-gold.jpg", alt: "Printed cushion with black palm-leaf and gold-leaf artwork on a white ground", layout: "photo-first", fit: "cover" },
  { product: allProducts.find((prod) => prod.slug === "tablecloth-natural"), title: "Printed tablecloths", meta: "Table Top Cover", image: "/images/products/tablecloth-natural.jpg", alt: "Natural print tablecloth from the Kitchen & Table Presentation catalogue", layout: "copy-first", fit: "cover" },
];
export function HomeBelowHero() {
  return <div className="aero-home-lower overflow-hidden">
    <section data-luxury-section="origin" className="aero-origin bg-ivory py-24 md:py-36"><Container><Reveal className="aero-origin__inner"><p className="aero-origin__label">[ About Aero Cotton ]</p><span className="aero-origin__drop" aria-hidden="true" /><h2 className="aero-origin__statement">We make cotton textiles with clarity and care &mdash; considered materials, dependable processes, everyday comfort.</h2><Link href="/about" className="aero-arrow-link aero-origin__link">About <span aria-hidden="true">&rarr;</span></Link></Reveal></Container></section>
    <section data-luxury-section="catalogue" className="aero-catalogue bg-ivory py-24 md:py-32"><Container><div className="aero-catalogue__heading"><Reveal><p className="eyebrow">01 / Catalogue</p><h2 className="mt-5 max-w-2xl font-display text-display-lg text-ink">Every weave we make.</h2></Reveal><Reveal delay={100}><Link href="/products" className="aero-catalogue__cta">Browse the catalogue <span aria-hidden="true">→</span></Link></Reveal></div><div className="aero-catalogue__grid">{catalogueRows.map(({ product, title, meta, image, alt, layout, fit }, index) => product && <Reveal key={product.slug} delay={index * 40} className="aero-catalogue-item"><Link href={`/products/${product.collectionSlug}/${product.slug}`} className={`aero-catalogue-row aero-catalogue-row--${layout}`}><div className={`aero-catalogue-row__media${fit === "contain" ? " aero-catalogue-row__media--contain" : ""}`}><img src={image} alt={alt} loading="lazy" /></div><div className="aero-catalogue-row__copy"><small className="aero-catalogue-row__kicker">{product.collectionName} collection</small><div className="aero-catalogue-row__body"><h3>{title}</h3><p className="aero-catalogue-row__meta">{product.name}</p><p className="aero-catalogue-row__foot">{meta}</p></div></div></Link></Reveal>)}</div></Container></section>
    <section data-luxury-section="proof" className="aero-proof-collage bg-parchment py-20 md:py-28"><Container><div className="aero-proof-collage__grid"><Reveal className="aero-proof-collage__visual aero-proof-collage__visual--loom"><img src="/images/editorial/weaver-at-loom.jpg" alt="A weaver throwing the shuttle on a traditional handloom, spools of coloured cotton beside the warp" /><span>Inside the making</span></Reveal><Reveal delay={100} className="aero-proof-collage__copy"><p className="eyebrow">02 / An established standard</p><h2 className="mt-5 font-display text-display-lg text-ink">Built with experience. Delivered to specification.</h2><div className="aero-proof-collage__stats">{confirmedStats.slice(0, 4).map((stat) => <div key={stat.label}><strong>{stat.value}</strong><span>{stat.label}</span></div>)}</div><p className="mt-7 text-sm/relaxed text-umber">{company.tagline}. From fibre selection to export packing, every programme is shaped around consistency, quality and the buyer&apos;s brief.</p></Reveal></div></Container></section>
    <section data-luxury-section="final" className="aero-final bg-ivory"><div className="aero-final__copy"><Reveal className="aero-final__inner"><span className="aero-final__wordmark">AEROCOTTON</span><p className="aero-final__kicker">03 / Manufacturer &amp; exporter</p><h2 className="aero-final__title">Textiles made with clarity.</h2><p className="aero-final__body">From Karur to spaces around the world, made around the way your textile needs to work &mdash; fibre selected, woven and finished under one roof.</p><Link href="/contact" className="aero-final__cta">Request a quote <span aria-hidden="true">→</span></Link></Reveal></div><div className="aero-final__media"><img src="/images/editorial/weaving-mill-loom.jpg" alt="Sunlit weaving looms with rolls of freshly woven cotton cloth" loading="lazy" /><span className="aero-final__caption">Karur / Tamil Nadu · Since {company.founded}</span></div></section>
    <section data-luxury-section="quote" className="aero-quote bg-parchment py-20 md:py-28"><Container><div className="grid gap-12 lg:grid-cols-12"><div className="lg:col-span-4"><p className="eyebrow">04 / Tell us what you are making</p><h2 className="mt-5 font-display text-display-md text-ink">Start with a brief.</h2><p className="mt-5 text-base/loose text-umber">Share the product intent, quantity, palette and delivery timeline.</p></div><div className="lg:col-span-7 lg:col-start-6"><RfqForm /></div></div></Container></section>
  </div>;
}
